pwd0 <- getwd()
setwd("../code_from_what_genotype_next/")
source("simulations.R")
setwd(pwd0)
rm(pwd0)
out <- readRDS("../data/out_cpms.rds")


Rprof("Simulations2")
sim <- simulate_population(out$MHN_transitionRateMatrix, n_samples = 10000)
Rprof(NULL)
x1 <- summaryRprof("Simulations2")
print(x1$by.total)
print(x1$sampling.time)

# Rprof("Simulations")
# sim <- simulate_population(out$MHN_transitionRateMatrix, n_samples = 10000)
# Rprof(NULL)
# x2 <- summaryRprof("Simulations")
# # print(x2$by.total)
# print(x2$sampling.time)


# print("===")
# Rprof("Process")
# trajs <- process_simulations(sim)
# Rprof(NULL)
# y <- summaryRprof("Process")
# # print(y$by.total)
# print(y$sampling.time)