## Build or grab the common base 0 image first
## docker build -f Dockerfile-evam-common-0 --tag rdiaz02/evam-common-0 .

FROM rdiaz02/evam-common-0:latest

## Taggin of this file: R-version_evamtools-version

######################################################################
######################################################################
#####
#####     Common to the two subsequent Dockerfiles: this
#####     is the evamtools package on its own
#####
######################################################################
######################################################################

## Copy a file used for testing
COPY Renviron.based_on_bioc /app/

## Copy the directory and install and test evamtools
COPY evamtools/ /app/evamtools/
COPY micin-aei.png /app/evamtools/inst/miscell/

RUN cd /app && \
    ## sed -i 's/this_string_to_be_replaced_by_git_hash/'"$GIT_HASH"'/' ./evamtools/inst/shiny-examples/evamtools/ui.R && \
    V_PKG=$(cat ./evamtools/DESCRIPTION | grep Version | cut -d' ' -f2) && \
    R --no-site-file --no-init-file CMD build evamtools && \
    R --no-site-file --no-init-file CMD INSTALL --install-tests evamtools_$V_PKG.tar.gz && \
    export TESTTHAT_CPUS=$(cat /proc/cpuinfo | awk '/^processor/{print $3}' | tail -n 1) && \
    R_ENVIRON_USER=./Renviron.based_on_bioc R --no-site-file --no-init-file CMD check --no-manual evamtools_$V_PKG.tar.gz


######################################################################
######################################################################
#####
#####     End common for the two subsequent Dockerfiles
#####
######################################################################
######################################################################
