## Build the common base image first
## docker build -f Dockerfile-evam-common --tag rdiaz02/evam-common .

FROM rdiaz02/evam-common

## Increase build number if you want to force rebuild from here on
ARG build=1

## Oncotree does not declare via NAMESPACE
## that it imports optim from stats. And this
## Rprofile has stats in search() with smaller index.

RUN echo ".First <- function() {library(methods); library(datasets); library(utils); library(grDevices); library(graphics); library(stats); library(shiny); library(evamtools); cat('Loaded evamtools\n');}" > /home/rstudio/.Rprofile

## Debugging errors: for example, start as
## sudo docker run -it --entrypoint bash evamrstudio
