if(FALSE) {
## Testing that cpm_access_genots_paths_w_simplified_OR gives same output as
## cpm_to_trans_mat_oncosimul, the function that uses OncoSimulR
test_that("Testing evamtools:::cpm_access_genots_paths_w_simplified_OR by comparing with
OncoSimulR's based cpm_to_trans_mat_oncosimul", {
    ## Recall evamtools:::cpm2tm <- cpm_to_trans_mat_oncosimul

    ## First, load a bunch of data structures
    ## Adapted from test.OT-CBN-trans-mat-against-oncosimul.R
    ## ex_dbn_*: output from running evam:::do_DBN with examples_csd
    ## examples_csd: list of cross sectional data sets
    ## examples_csd: is located in file /data/examples_csd.RData
    ## examples_csd: is generated by script inst/miscell/toy_datasets.R


    data(examples_csd)
    ## Run HESBCN.
    ex_dbn_and <- evamtools:::do_DBN(examples_csd$csd$AND$data)
    ex_dbn_linear <- evamtools:::do_DBN(examples_csd$csd$Linear$data)
    ex_dbn_or <- evamtools:::do_DBN(examples_csd$csd$OR$data)
    ex_dbn_xor <- evamtools:::do_DBN(examples_csd$csd$XOR$data)
    ex_dbn_c1 <- evamtools:::do_DBN(examples_csd$csd$c1$data)
    ex_dbn_c3 <- evamtools:::do_DBN(examples_csd$csd$c3$data)
    ex_dbn_c4c2 <- evamtools:::do_DBN(examples_csd$csd$c4c2$data)
    

    all_examples <- list(ex_dbn_and, ex_dbn_linear, ex_dbn_or, ex_dbn_xor,
        ex_dbn_c1, ex_dbn_c3, ex_dbn_c4c2)

    ## For testing
    reorder_trans_mat <- function(x) {
        gg <- c(1, 1 + order(colnames(x)[-1]))
        return(as.matrix(x[gg, gg]))
    }

    run_test_for_dataset <- function(data){
        expect_equal(reorder_trans_mat(evamtools:::cpm2tm(data$edges, max_f = NULL)$transition_matrix),
                    reorder_trans_mat(evamtools:::cpm_access_genots_paths_w_simplified_OR(
                        data)$trans_mat_genots),
                    check.attributes = TRUE)
        maxff <- sample(c(2, 3, 3.5, 3.8, 4, 5, 8), size = 1)
        expect_equal(as.matrix(evamtools:::cpm2tm(data$edges, max_f = NULL)$transition_matrix),
                    as.matrix(evamtools:::cpm2tm(data$edges, max_f = maxff)$transition_matrix))
    }

    for(i in all_examples){
        run_test_for_dataset(i)
    }
    
    ## Repeat with some examples from real data sets
    data(every_which_way_data)

    dd <- list(
        Dat1 = every_which_way_data[[2]][1:50, 1:4]
      , Dat2 = every_which_way_data[[4]][1:50, 1:5]
      , Dat3 = every_which_way_data[[20]][1:50, 1:5]
      , Dat4 = every_which_way_data[[16]][1:40, 2:6] ## yes, last is 0
      , Dat5 = every_which_way_data[[2]][ , 1:7]
      , Dat6 = every_which_way_data[[4]][1:60, 1:7]
      , Dat7 = every_which_way_data[[20]][, 1:7]
      , Dat8 = every_which_way_data[[16]][, 1:7]
    )

    dd <- lapply(dd, function(z) {
        tmp <- evamtools:::df_2_mat_integer(z)
        tmp <- evamtools:::pre_process(tmp, remove.constant = FALSE)
        return(tmp)
    })
        
    out_dd <- lapply(dd, evamtools:::do_DBN)

    ## The last four are slow tests
    for(i in seq_along(out_dd)) {
        run_test_for_dataset(out_dd[[i]])
    }


    ## Add the examples used for HESBCN with mixes of relationships
    set.seed(2)
    d1 <- data.frame(A = sample(c(1, 0), prob = c(0.7, 0.2), size = 200, replace = TRUE),
                     B = sample(c(1, 0), prob = c(0.85, 0.2), size = 200, replace = TRUE))
    d1$C <- 0
    d1$D <- 0
    d1$E <- 0
    d1$F <- 0
    d1$C[(d1$A == 1) & (d1$B == 1)] <- 1
    d1$D[(d1$A == 1) | (d1$B == 1)] <- 1
    d1$D[100:200] <- 0
    d1$E[xor((d1$A == 1), (d1$B == 1))] <- 1
    d1$F[(d1$C == 1) & (d1$D == 1)] <- 1
    d2 <- rbind(d1,
                data.frame(A = sample(c(1, 0), size = 25, prob = c(0.5, 0.2), replace = TRUE),
                           B = sample(c(1, 0), size = 25, prob = c(0.5, 0.2), replace = TRUE),
                           C = 0,
                           D = sample(c(1, 0), size = 25, replace = TRUE),
                           E = 0,
                           F = 0))
    d3 <- d2
    d3$C[(d3$A == 1) & (d3$B == 1)] <- 1
    
    set.seed(22)
    d111 <- data.frame(A = sample(c(1, 0), prob = c(0.7, 0.2), size = 2000, replace = TRUE),
                     B = sample(c(1, 0), prob = c(0.85, 0.2), size = 2000, replace = TRUE))
    d111$C <- 0
    d111$D <- 0
    d111$E <- 0
    d111$F <- 0
    d111$C[(d111$A == 1) & (d111$B == 1)] <- 1
    d111$D[(d111$A == 1) | (d111$B == 1)] <- 1
    d111$D[100:200] <- 0
    d111$E[xor((d111$A == 1), (d111$B == 1))] <- 1
    d111$F[(d111$C == 1) & (d111$D == 1)] <- 1
    d222 <- rbind(d111,
                data.frame(A = sample(c(1, 0), size = 250, prob = c(0.5, 0.2), replace = TRUE),
                           B = sample(c(1, 0), size = 250, prob = c(0.5, 0.2), replace = TRUE),
                           C = 0,
                           D = sample(c(1, 0), size = 25, replace = TRUE),
                           E = 0,
                           F = 0))
    d333 <- d222
    d333$C[(d333$A == 1) & (d333$B == 1)] <- 1

    set.seed(NULL)
    
    d3_1 <- evamtools:::do_DBN(d3)
    d2_1 <- evamtools:::do_DBN(d2)
    d222_1 <- evamtools:::do_DBN(d222)
    d333_1 <- evamtools:::do_DBN(d333)

    all_mixed_examples <- list(d3_1, d2_1, d222_1, d333_1)
    
    for(ex in all_mixed_examples){
        run_test_for_dataset(ex)
    }
    set.seed(NULL)

    
})

cat("\n Done test.DBN-trans-mat-against-oncosimul.R \n")


}
