## Testing that cpm_access_genots_paths_w_simplified_OR gives same output as
## cpm_to_trans_mat_oncosimul, the function that uses OncoSimulR
test_that("Testing evamtools:::cpm_access_genots_paths_w_simplified_OR by comparing with
OncoSimulR's based cpm_to_trans_mat_oncosimul", {
    ## Recall evamtools:::cpm2tm <- cpm_to_trans_mat_oncosimul

    ## First, load a bunch of data structures
    ## Adapted from test.OT-CBN-trans-mat-against-oncosimul.R
    ## ex_dbn_*: output from running evam:::do_DBN with examples_csd
    ## examples_csd: list of cross sectional data sets
    ## examples_csd: is located in file /data/all_examples_csd.RData
    ## examples_csd: is generated by script inst/miscell/toy_datasets.R

    ## Output from running evamtools:::do_DBN(examples_csd$csd$AND$data)
    ex_dbn_and <- list(edges = structure(list(From = c("Root", "A", "B", "C", "B"),
                                  To = c("A", "B", "C", "D", "D"),
                                  Edge = c("Root -> A", 
                                  "A -> B",
                                  "B -> C",
                                  "C -> D",
                                  "B -> D"),
                                  Thetas = c(0.97872340, 0.34782609, 0.37500000, 0.03846154, 0.03846154)),
                                class = "data.frame"
                                , row.names = c(NA, -5L)
                                )
                            )

    ## Output from running evamtools:::do_DBN(examples_csd$csd$Linear$data)
    ex_dbn_linear <- list(edges = structure(list(From = c("Root", "A", "B", "C"),
                                  To = c("A", "B", "C", "D"),
                                  Edge = c("Root -> A", "A -> B", "B -> C", "C -> D"),
                                  Thetas = c(0.9756098, 0.7500000, 0.6666667, 0.5000000)),
                                class = "data.frame", row.names = c("A", "B", "C", "D")
                                )
                            )

    ## Output from running evamtools:::do_DBN(examples_csd$csd$OR$data)
    ex_dbn_or <- list(edges = structure(list(From = c("Root", "D", "D", "B", "Root"),
                                  To = c("A", "B", "C", "C", "D"),
                                  Edge = c("Root -> A", 
                                  "D -> B",
                                  "D -> C",
                                  "B -> C",
                                  "Root -> D"),
                                  Thetas = c(0.9824561, 0.5454545, 0.4230769, 0.4230769, 0.1929825)),
                                  class = "data.frame"
                                , row.names = c(NA, -4L)
                                ) 
                            ) 

    ## Output from running evamtools:::do_DBN(examples_csd$csd$XOR$data)
    ex_dbn_xor <- list(edges = structure(list(From = c("Root", "D", "D", "Root"),
                                  To = c("A", "B", "C", "D"),
                                  Edge = c("Root -> A", 
                                  "D -> B",
                                  "D -> C",
                                  "Root -> D"),
                                  Thetas = c(0.9803922, 0.5000000, 0.5000000, 0.1960784)),
                                  class = "data.frame"
                                , row.names = c(NA, -4L)
                                ) 
                            )   
    ## Output from running evamtools:::do_DBN(examples_csd$csd$c1$data)
    ex_dbn_c1 <- list(edges = structure(list(From = c("Root", "E", "A", "Root", "E", "C", "C", "A"),
                                  To = c("A", "B", "B", "C", "D", "D", "E", "E"),
                                  Edge = c("Root -> A", 
                                  "E -> B",
                                  "A -> B",
                                  "Root -> C",
                                  "E -> D",
                                  "C -> D",
                                  "C -> E",
                                  "A -> E"),
                                  Thetas = c(0.6325301, 0.4782609, 0.4782609, 0.6325301,
                                     0.4782609, 0.4782609, 0.2424242, 0.2424242)),
                                  class = "data.frame"
                                , row.names = c(NA, -8L)
                                ) 
                            )   

    ## Output from running evamtools:::do_DBN(examples_csd$csd$c3$data)
    ex_dbn_c3 <- list(edges = structure(list(From = c("Root", "A", "E", "C", "B", "A"),
                                  To = c("A", "B", "C", "D", "E", "E"),
                                  Edge = c("Root -> A", 
                                  "A -> B",
                                  "E -> C",
                                  "C -> D",
                                  "B -> E",
                                  "A -> E"),
                                  Thetas = c(0.3314917, 0.5000000, 0.5000000, 0.5000000, 0.1111111, 0.1111111)),
                                  class = "data.frame"
                                , row.names = c(NA, -6L)
                                )
                            ) 
    
    ## Output from running evamtools:::do_DBN(examples_csd$csd$c4c2$data)
    ex_dbn_c4c2 <- list(edges = structure(list(From = c("Root", "C", "A", "Root", "C", "A"),
                                  To = c("A", "B", "B", "C", "D", "D"),
                                  Edge = c("Root -> A", 
                                  "C -> B",
                                  "A -> B",
                                  "Root -> C",
                                  "C -> D",
                                  "A -> D",
                                  "D -> E"),
                                  Thetas = c(0.5952381, 0.2800000, 0.2800000, 0.5952381, 0.2800000, 0.2800000)),
                                  class = "data.frame"
                                , row.names = c(NA, -6L)
                                )
                            ) 

    all_examples <- list(ex_dbn_and, ex_dbn_linear, ex_dbn_or, ex_dbn_xor,
        ex_dbn_c1, ex_dbn_c3, ex_dbn_c4c2)

    ## For testing
    reorder_trans_mat <- function(x) {
        gg <- c(1, 1 + order(colnames(x)[-1]))
        return(as.matrix(x[gg, gg]))
    }

    run_test_for_dataset <- function(data){
        ## Same transitions, different fitness
        evamtools:::cpm2tm(data$edges, max_f = NULL)$transition_matrix
        evamtools:::cpm2tm(data$edges, 8)$transition_matrix

        ## Original code
        evamtools:::cpm_access_genots_paths_w_simplified_OR(data)$trans_mat_genots
        
        ## CBN
        expect_equal(reorder_trans_mat(evamtools:::cpm2tm(data$edges, max_f = NULL)$transition_matrix),
                    reorder_trans_mat(evamtools:::cpm_access_genots_paths_w_simplified_OR(
                        data)$trans_mat_genots),
                    check.attributes = TRUE)

        expect_equal(as.matrix(evamtools:::cpm2tm(data$edges, max_f = NULL)$transition_matrix),
                    as.matrix(evamtools:::cpm2tm(data$edges, max_f = 2)$transition_matrix))
    }

    for(i in all_examples){
        run_test_for_dataset(i)
    }
})

cat("\n Done test.DBN-output2oncosimul.R \n")


