## Testing that cpm_access_genots_paths_w_simplified_relationships gives same output as
## cpm_to_trans_mat_oncosimul, the function that uses OncoSimulR
test_that("Testing evamtools:::cpm_access_genots_paths_w_simplified_relationships by comparing with
OncoSimulR's based cpm_to_trans_mat_oncosimul", {
    ## Recall evamtools:::cpm2tm <- cpm_to_trans_mat_oncosimul

    ## First, load a bunch of data structures
    ## Adapted from test.OT-CBN-trans-mat-against-oncosimul.R
    ## ex_hesbcn_*: output from running evam:::do_HESBCN with examples_csd
    ## examples_csd: list of cross sectional data sets
    ## examples_csd: is located in file /data/all_examples_csd.RData
    ## examples_csd: is generated by script inst/miscell/toy_datasets.R

    ## Output from running evamtools:::do_HESBCN(examples_csd$csd$AND$data)
    ex_hesbcn_and <- list(edges = structure(list(From = c("Root", "A", "A", "B", "C"),
                                  To = c("A", "B", "C", "D", "D"),
                                  Edge = c("Root -> A", 
                                  "A -> B",
                                  "A -> C",
                                  "B -> D",
                                  "C -> D"),
                                  Lambdas = c(41.607, 0.509, 0.509, 0.100, 0.100)),
                                class = "data.frame"
                                , row.names = c(NA, -5L)
                                ) ,
                            parent_set = structure(c("Single", "Single", "Single", "AND"),
                                class = "list", names = c("A", "B", "C", "D"))
                            )

    ## Output from running evamtools:::do_HESBCN(examples_csd$csd$Linear$data)
    ex_hesbcn_linear <- list(edges = structure(list(From = c("Root", "A", "B", "C"),
                                  To = c("A", "B", "C", "D"),
                                  Edge = c("Root -> A", "A -> B", "B -> C", "C -> D"),
                                  Lambdas = c(36.25090, 3.00034, 2.00026, 1.00019)),
                                class = "data.frame", row.names = c("A", "B", "C", "D")
                                ) ,
                            parent_set = structure(c("Single", "Single","Single", "Single"),
                                class = "list", names = c("A", "B", "C", "D"))
                            )

    ## Output from running evamtools:::do_HESBCN(examples_csd$csd$OR$data)
    ex_hesbcn_or <- list(edges = structure(list(From = c("Root", "A", "A", "B", "C"),
                                  To = c("A", "B", "C", "D", "D"),
                                  Edge = c("Root -> A", 
                                  "A -> B",
                                  "A -> C",
                                  "B -> D",
                                  "C -> D"),
                                  Lambdas = c(50.467200, 0.535712, 0.535712, 0.260448, 0.260448)),
                                  class = "data.frame"
                                , row.names = c(NA, -5L)
                                ) ,
                            parent_set = structure(c("Single", "Single", "Single", "OR"),
                                class = "list", names = c("A", "B", "C", "D"))
                            ) 

    ## Output from running evamtools:::do_HESBCN(examples_csd$csd$XOR$data)
    ex_hesbcn_xor <- list(edges = structure(list(From = c("Root", "A", "A", "B", "C"),
                                  To = c("A", "B", "C", "D", "D"),
                                  Edge = c("Root -> A", 
                                  "A -> B",
                                  "A -> C",
                                  "B -> D",
                                  "C -> D"),
                                  Lambdas = c(10.74330, 1.40714, 1.40714, 1.09555, 1.09555)),
                                  class = "data.frame"
                                , row.names = c(NA, -5L)
                                ) ,
                            parent_set = structure(c("Single", "Single", "Single", "XOR"),
                                class = "list", names = c("A", "B", "C", "D"))
                            )   
    ## Output from running evamtools:::do_HESBCN(examples_csd$csd$c1$data)
    ex_hesbcn_c1 <- list(edges = structure(list(From = c("Root", "A", "Root", "C", "B", "D"),
                                  To = c("A", "B", "C", "D", "E", "E"),
                                  Edge = c("Root -> A", 
                                  "A -> B",
                                  "Root -> C",
                                  "C -> D",
                                  "B -> E",
                                  "D -> E"),
                                  Lambdas = c(1.041270, 4.341490, 1.041270, 4.341490, 1.842265, 1.842265)),
                                  class = "data.frame"
                                , row.names = c(NA, -6L)
                                ) ,
                            parent_set = structure(c("Single", "Single", "Single", "Single", "XOR"),
                                class = "list", names = c("A", "B", "C", "D", "E"))
                            )   

    ## Output from running evamtools:::do_HESBCN(examples_csd$csd$c3$data)
    ex_hesbcn_c3 <- list(edges = structure(list(From = c("Root", "A", "Root", "C", "B", "D"),
                                  To = c("A", "B", "C", "D", "E", "E"),
                                  Edge = c("Root -> A", 
                                  "A -> B",
                                  "Root -> C",
                                  "C -> D",
                                  "B -> E",
                                  "D -> E"),
                                  Lambdas = c(1.041270, 4.341490, 1.041270, 4.341490, 1.842265, 1.842265)),
                                  class = "data.frame"
                                , row.names = c(NA, -6L)
                                ) ,
                            parent_set = structure(c("Single", "Single", "Single", "Single", "XOR"),
                                class = "list", names = c("A", "B", "C", "D", "E"))
                            ) 
    
    ## Output from running evamtools:::do_HESBCN(examples_csd$csd$c4c2$data)
    ex_hesbcn_c4c2 <- list(edges = structure(list(From = c("Root", "A", "Root", "C"),
                                  To = c("A", "B", "C", "D"),
                                  Edge = c("Root -> A", 
                                  "A -> B",
                                  "Root -> C",
                                  "C -> D"),
                                  Lambdas = c(1.01822, 1.20561, 1.01822, 1.20561)),
                                  class = "data.frame"
                                , row.names = c("A", "B", "C", "D")
                                ) ,
                            parent_set = structure(c("Single", "Single", "Single", "Single"),
                                class = "list", names = c("A", "B", "C", "D"))
                            ) 

    all_examples <- list(ex_hesbcn_and, ex_hesbcn_linear, ex_hesbcn_or, ex_hesbcn_xor,
        ex_hesbcn_c1, ex_hesbcn_c3, ex_hesbcn_c4c2)

    ## For testing
    reorder_trans_mat <- function(x) {
        gg <- c(1, 1 + order(colnames(x)[-1]))
        return(as.matrix(x[gg, gg]))
    }

    run_test_for_dataset <- function(data){
        data$edges$Relation <- sapply(
                data$edges$To,
                function(x) data$parent_set[x]
            )
        ## Same transitions, different fitness
        evamtools:::cpm2tm(data$edges, max_f = NULL)$transition_matrix
        evamtools:::cpm2tm(data$edges, 8)$transition_matrix

        ## Original code
        evamtools:::cpm_access_genots_paths_w_simplified_relationships(data)$trans_mat_genots
        
        expect_equal(reorder_trans_mat(evamtools:::cpm2tm(data$edges, max_f = NULL)$transition_matrix),
                    reorder_trans_mat(evamtools:::cpm_access_genots_paths_w_simplified_relationships(
                        data)$trans_mat_genots),
                    check.attributes = TRUE)

        expect_equal(as.matrix(evamtools:::cpm2tm(data$edges, max_f = NULL)$transition_matrix),
                    as.matrix(evamtools:::cpm2tm(data$edges, max_f = 2)$transition_matrix))
    }

    for(i in all_examples){
        run_test_for_dataset(i)
    }
})
cat("\n Done test.HESBCN-output2oncosimul.R \n")

