## Testing that cpm_access_genots_paths_w_simplified_relationships gives same output as
## cpm_to_trans_mat_oncosimul, the function that uses OncoSimulR

## FIXME: once everything has been tested and running for a while, rm some of the
## tests below (from real data), as way to slow and probably overkill

test_that("Testing evamtools:::cpm_access_genots_paths_w_simplified_relationships by comparing with
OncoSimulR's based cpm_to_trans_mat_oncosimul", {
    ## Recall evamtools:::cpm2tm <- cpm_to_trans_mat_oncosimul

    ## For testing
    reorder_trans_mat <- function(x) {
        gg <- c(1, 1 + order(colnames(x)[-1]))
        return(as.matrix(x[gg, gg]))
    }

    run_test_for_dataset <- function(data) {
        expect_equal(
            reorder_trans_mat(evamtools:::cpm2tm(data$edges, max_f = NULL)$transition_matrix),
            reorder_trans_mat(evamtools:::cpm_access_genots_paths_w_simplified_relationships(
                                              data)$trans_mat_genots),
            check.attributes = TRUE)

        ## Do not run next test if fitness is absurdly large as scaling will fail
        ## as it should.
        max_fitness <- max(evamtools:::cpm2tm(data$edges, max_f = NULL)$accessible_genotypes)
        if(max_fitness < 1e10) {
            expect_equal(as.matrix(evamtools:::cpm2tm(data$edges, max_f = NULL)$transition_matrix),
                         as.matrix(evamtools:::cpm2tm(data$edges, max_f = 2)$transition_matrix))
        }
    }
    
    ## First, load a bunch of data structures
    ## Adapted from test.OT-CBN-trans-mat-against-oncosimul.R
    ## ex_hesbcn_*: output from running evam:::do_HESBCN with examples_csd
    ## examples_csd: list of cross sectional data sets
    ## examples_csd: is located in file /data/all_examples_csd.RData
    ## examples_csd: is generated by script inst/miscell/toy_datasets.R

    ## Output from running evamtools:::do_HESBCN(examples_csd$csd$AND$data)

    data(all_examples_csd)
    ## Run HESBCN.
    ex_hesbcn_and <- evamtools:::do_HESBCN(examples_csd$csd$AND$data)
    ex_hesbcn_linear <- evamtools:::do_HESBCN(examples_csd$csd$Linear$data)
    ex_hesbcn_or <- evamtools:::do_HESBCN(examples_csd$csd$OR$data)
    ex_hesbcn_xor <- evamtools:::do_HESBCN(examples_csd$csd$XOR$data)
    ex_hesbcn_c1 <- evamtools:::do_HESBCN(examples_csd$csd$c1$data)
    ex_hesbcn_c3 <- evamtools:::do_HESBCN(examples_csd$csd$c3$data)
    ex_hesbcn_c4c2 <- evamtools:::do_HESBCN(examples_csd$csd$c4c2$data)

   
    
    all_examples <- list(ex_hesbcn_and, ex_hesbcn_linear, ex_hesbcn_or, ex_hesbcn_xor,
        ex_hesbcn_c1, ex_hesbcn_c3, ex_hesbcn_c4c2)

    

    for(i in all_examples){
        run_test_for_dataset(i)
    }


    ## Create two data sets that tend to lead to combination of AND, OR, XOR,
    ## Single.

    ## And if you thought CBN was unstable and sometimes counterintuitive ... try
    ## HESBCN :-)
    
    set.seed(2)
    d1 <- data.frame(A = sample(c(1, 0), prob = c(0.7, 0.2), size = 200, replace = TRUE),
                     B = sample(c(1, 0), prob = c(0.85, 0.2), size = 200, replace = TRUE))
    d1$C <- 0
    d1$D <- 0
    d1$E <- 0
    d1$F <- 0
    d1$C[(d1$A == 1) & (d1$B == 1)] <- 1
    d1$D[(d1$A == 1) | (d1$B == 1)] <- 1
    d1$D[100:200] <- 0
    d1$E[xor((d1$A == 1), (d1$B == 1))] <- 1
    d1$F[(d1$C == 1) & (d1$D == 1)] <- 1
    d2 <- rbind(d1,
                data.frame(A = sample(c(1, 0), size = 25, prob = c(0.5, 0.2), replace = TRUE),
                           B = sample(c(1, 0), size = 25, prob = c(0.5, 0.2), replace = TRUE),
                           C = 0,
                           D = sample(c(1, 0), size = 25, replace = TRUE),
                           E = 0,
                           F = 0))
    d3 <- d2
    d3$C[(d3$A == 1) & (d3$B == 1)] <- 1
    
    set.seed(22)
    d111 <- data.frame(A = sample(c(1, 0), prob = c(0.7, 0.2), size = 2000, replace = TRUE),
                     B = sample(c(1, 0), prob = c(0.85, 0.2), size = 2000, replace = TRUE))
    d111$C <- 0
    d111$D <- 0
    d111$E <- 0
    d111$F <- 0
    d111$C[(d111$A == 1) & (d111$B == 1)] <- 1
    d111$D[(d111$A == 1) | (d111$B == 1)] <- 1
    d111$D[100:200] <- 0
    d111$E[xor((d111$A == 1), (d111$B == 1))] <- 1
    d111$F[(d111$C == 1) & (d111$D == 1)] <- 1
    d222 <- rbind(d111,
                data.frame(A = sample(c(1, 0), size = 250, prob = c(0.5, 0.2), replace = TRUE),
                           B = sample(c(1, 0), size = 250, prob = c(0.5, 0.2), replace = TRUE),
                           C = 0,
                           D = sample(c(1, 0), size = 25, replace = TRUE),
                           E = 0,
                           F = 0))
    d333 <- d222
    d333$C[(d333$A == 1) & (d333$B == 1)] <- 1

    set.seed(NULL)
    
    ## Examples that mix output
    d3_1 <- evamtools:::do_HESBCN(d3, seed = 1) ## AND, OR,XOR, Single
    d3_2 <- evamtools:::do_HESBCN(d3, seed = 6)
    d3_3 <- evamtools:::do_HESBCN(d3, seed = 7)
    ## d3_4 <- evamtools:::do_HESBCN(d3, seed = 8)
    ## d333_1 <- evamtools:::do_HESBCN(d333, seed = 6) ## single, OR, XOR
    d333_2 <- evamtools:::do_HESBCN(d333, seed = 222) ## single, OR, XOR, AND

    all_mixed_examples <- list(d3_1, d3_2, d3_3, d3_3, d333_2)
    
    for(ex in all_examples){
        run_test_for_dataset(ex)
    }
    set.seed(NULL)
    
    ## Doesn't give us much, since most are Single
    ## ## Repeat with some examples from real data sets
    ## data(every_which_way_data)

    ## dd <- list(
    ##     Dat1 = every_which_way_data[[2]][1:50, 1:4]
    ##   , Dat2 = every_which_way_data[[4]][1:50, 1:5]
    ##   , Dat3 = every_which_way_data[[20]][1:50, 1:5]
    ##   , Dat4 <- every_which_way_data[[16]][1:40, 2:6]
    ##   , Dat5 = every_which_way_data[[2]][ , 1:7]
    ##   , Dat6 = every_which_way_data[[4]][1:60, 1:7]
    ##   , Dat7 = every_which_way_data[[20]][, 1:7]
    ##   , Dat8 = every_which_way_data[[16]][, 1:7]
    ## )

    ## dd <- lapply(dd, function(z) {
    ##     tmp <- evamtools:::df_2_mat_integer(z)
    ##     tmp <- evamtools:::pre_process(tmp, remove.constant = FALSE)
    ##     return(tmp)
    ## })
    
    ## out_dd <- lapply(dd, evamtools:::do_HESBCN)

    ## ## The last four are slow tests
    ## for(i in seq_along(out_dd)) {
    ##     run_test_for_dataset(out_dd[[i]])
    ## }

    
})





## test_that("Testing evamtools:::cpm_access_genots_paths_w_simplified_relationships
## by comparing with
## OncoSimulR's based cpm_to_trans_mat_oncosimul. Use the CBN examples", {

##     ## HESBCN relationships are a superset of those in CBN. Thus, the
##     ## examples in test.OT-CBN-trans.mat-against-oncosimul.R for CBN
##     ## should also be handled identically by the code for HESBCN.

##     ## Required changes:
##     ##   - use only "rerun_lambda" and rename to "Lambdas"
##     ##   - parent_set: create and set to AND

##     ## For testing
##     reorder_trans_mat <- function(x) {
##         gg <- c(1, 1 + order(colnames(x)[-1]))
##         return(as.matrix(x[gg, gg]))
##     }

##     fcomp <- function(zz) {
        
##         expect_equal(reorder_trans_mat(evamtools:::cpm2tm(zz, max_f = NULL)$transition_matrix),
##                  reorder_trans_mat(evamtools:::cpm_access_genots_paths_w_simplified_relationships(
##                      list(edges = zz))$trans_mat_genots),
##                  check.attributes = TRUE)
##         expect_equal(as.matrix(evamtools:::cpm2tm(zz$edges, max_f = NULL)$transition_matrix),
##                     as.matrix(evamtools:::cpm2tm(zz$edges, max_f = 2)$transition_matrix))
##     }

    
##     ex_cbn_out1 <- list(edges = structure(list(From = c("Root", "Root"),
##                                   To = c("A", "B"),
##                                   edge = c("Root -> A", "Root -> B"),
##                                   Lambdas = c(88.234297, 268.921382)),
##                                   class = "data.frame",
##                                   row.names = c("A", "B")),
##                         parent_set =
##                             structure(
##                                 c("AND", "AND"),
##                                 class = "list",
##                                 names = c("A", "B")))

   
    
##      expect_equal(reorder_trans_mat(evamtools:::cpm2tm(ex_cbn_out1, max_f = NULL)$transition_matrix),
##                  reorder_trans_mat(evamtools:::cpm_access_genots_paths_w_simplified_relationships(
##                      list(edges = ex_cbn_out1))$trans_mat_genots),
##               check.attributes = TRUE)
  

##     run_test_for_dataset <- function(data){
        
##         ## Same transitions, different fitness
##         evamtools:::cpm2tm(data$edges, max_f = NULL)$transition_matrix
##         evamtools:::cpm2tm(data$edges, 8)$transition_matrix

##         ## Original code
##         evamtools:::cpm_access_genots_paths_w_simplified_relationships(data)$trans_mat_genots
        
##         expect_equal(reorder_trans_mat(evamtools:::cpm2tm(data$edges, max_f = NULL)$transition_matrix),
##                     reorder_trans_mat(evamtools:::cpm_access_genots_paths_w_simplified_relationships(
##                         data)$trans_mat_genots),
##                     check.attributes = TRUE)

##         expect_equal(as.matrix(evamtools:::cpm2tm(data$edges, max_f = NULL)$transition_matrix),
##                     as.matrix(evamtools:::cpm2tm(data$edges, max_f = 2)$transition_matrix))
##     }

##     for(i in all_examples){
##         run_test_for_dataset(i)
##     }
## })


cat("\n Done test.HESBCN-trans-mat-against-oncosimul.R \n")




